version: '3.7'
services:
  spark-master:
    image: spark
    container_name: spark-master
    entrypoint: ['./entrypoint.sh', 'master']
    build:
      - context: ./
      - dockerfile: Dockerfile_prod_test
    ports:
      - "4040:4040" # tcp
      - "8080:8080" # http
      - "3000:3000" # tcp
      - "7077:7077" # spark master
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./scripts/src:/opt/spark/work-dir/src
      - ./scripts/data:/opt/spark/work-dir/data
      - ./scripts/spark-logs:/opt/spark/logs

  spark-worker:
    image: spark
    container_name: spark-worker
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./scripts/src:/opt/spark/work-dir/src
      - ./scripts/data:/opt/spark/work-dir/data
      - ./scripts/spark-logs:/opt/spark/logs

  spark-history-server:
    container_name: spark-history
    image: spark
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    volumes:
      - ./scripts/spark-logs:/opt/spark/logs
    ports:
      - '18080:18080'